api:
   test:
      response: This is the value at git repo centralconfrepo USING-FEIGN4.10
spring:
  cloud:
    inetutils:
      ignoredInterfaces:
        - docker0
        - docker_gwbridge
        - lo
        - veth*    
      preferredNetworks:
        - 192.168
        - 10.0
eureka:
  instance:
    instance-id: ${spring.cloud.client.hostname}:${spring.application.name}:${spring.application.instance_id:${server.port}:${random.value}}  
    preferIpAddress: true
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
  client:
    registerWithEureka: true
    fetchRegistry: true
    registryFetchIntervalSeconds: 3
    shouldDisableDelta: true
    serviceUrl:
       defaultZone: http://eureka:eureka@eureka:8761/eureka/,http://eureka:eureka@eureka-backup:8762/eureka/
ribbon:
  eureka:
    enabled: true
